org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_id=shincolle
mod_version=1.20.1.0.8.1
mod_group_id=com.lulan.shincolle
mod_authors=PinkaLulan
mod_description=Collect cute SeiKan mobs! A Minecraft mod featuring ship girl entities.
mod_license=All Rights Reserved

# Minecraft / Forge
minecraft_version=1.20.1
forge_version=47.4.0
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Loader
loader_version_range=[47,)
forge_version_range=[47,)
minecraft_version_range=[1.20.1,1.20.2)
